### ISSUE TITLE
Kernel and Mellanox Ofed Driver Versions

### ISSUE THREAD

**Issue by baber-sos** [larrystevenwise/krping#5]
Can you please tell the driver version for the mellanox drivers used for Makefile patching to be successful?

Regards

**Comment by larrystevenwise** [comment]
I don't understand.  What are you asking for exactly?  What does the driver version have to do with anything?  Please explain the issue further.  Thanks!

**Comment by larrystevenwise** [comment]
krping is intended to be used on upstream kernels.  I don't support OFED nor MOFED anymore.  Thanks!
