### ISSUE TITLE
Compiling krping on CentOS 8 (RHEL8)

### ISSUE THREAD

**Issue by PsFreedom** [larrystevenwise/krping#7]
Hi,
I try krping on the latest CentOS 8.2 (RHEL8) with the Mellanox OFED driver 5.0 
(Driver: https://www.mellanox.com/products/infiniband-drivers/linux/mlnx_ofed)

However, I cannot make krping properly and install-ofa.sh script does not work either.

The ofa kernel tree seems to be located at /usr/src/ofa_kernel-5.0
It does not have "compat-rdma" directory but it contains several other "compat" directories inside.

Please let me know if we can fix this issue.
And do you have any plan to update the script or support more recent Linux and Driver?

Thank you very much.

**Comment by larrystevenwise** [comment]
Hey,  sorry for the ultra-slow response!  I don't plan to support OFED any more.  Just top-of-tree linux kernel. 

Steve.
